# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CheckoutRepo
    jobs:
      - job: checkoutRepo
        steps:
          - checkout: self
          - bash: echo "###Azure Repo Checkout###"

  - stage: PrepPlaybook
    jobs:
      - job: prepPlaybook
        steps:
        - script: pip install ansible[azure]
          displayName: 'Install Ansible and the Azure modules'
          condition: 

  - stage: RunPlaybook
    jobs:
      - job: runPlaybook
        steps:
        - script: ansible-playbook ansible-create-queues.yml -i ansible-inventory.ini
          displayName: 'Run Ansible Playbook'