# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

parameters:
- name: serviceSelection
  type: string
  values:
    - localhost
    - nram-dev1.messaging.solace.cloud
    - nram-dev2-aws-ohio.messaging.solace.cloud
  default: nram-dev2-aws-ohio.messaging.solace.cloud

variables:
 - group: ${{ parameters.serviceSelection }}

stages:
  - stage: checkoutRepo
    jobs:
      - job: checkoutRepo
        steps:
          - checkout: self
          - bash: echo "###Azure Repo Checkout###"
  
  - stage: provisionQueuePrep
    jobs:
    - job: provisionQueuePrep
      steps:
        - script: echo creating queue prep
        - bash: |
            echo "HOST : $HOST"
            echo "SEMPUSER: $SEMPUSER"

  - stage: provisionQueue
    jobs:
    - job: provisionQueue
      steps:
      - task: PythonScript@0
        inputs:
          scriptSource: 'filePath' # Options: filePath, inline
          scriptPath: scripts/provision-queue.py
          arguments: --host $(HOST) --user $(SEMPUSER) --pass $(SEMPPASS)
          #pythonInterpreter: # Optional
          #workingDirectory: # Optional
          #failOnStderr: false # Optional
